>> config-base.yml
>>| 16
  # Some hosting services change your Java port everytime you start the server and require the same port to be used for Bedrock.
  # This option makes the Bedrock port the same as the Java port every time you start the server.
  # This option is for the plugin version only.
  clone-remote-port: false
>>|
>>| 35
  # Floodgate will be detected automatically if Floodgate is also installed on this server
>>|
>>| 78
# Enable LEGACY ping passthrough. There is no need to enable this unless your MOTD or player count does not appear properly.
legacy-ping-passthrough: false
>>|
>>| 192
# Whether to connect directly into the Java server without creating a TCP connection.
# This should only be disabled if a plugin that interfaces with packets or the network does not work correctly with Geyser.
# If enabled: the remote address and port sections are ignored.
# If disabled: expect performance decrease and latency increase.
use-direct-connection: true

>>|
>>*