name: Build Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Check if the author has forked the API repo
        uses: Kas-tle/ForkFinder@v1.0.1
        id: find_forks
        with:
          owner: GeyserMC
          repo: api
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout author's API repo if it exists
        uses: actions/checkout@v3
        if: steps.find_forks.outputs.target_branch_found == 'true'
        env:
          API_FORK_URL: ${{ steps.find_forks.outputs.user_fork_url }}
          API_FORK_BRANCH: ${{ github.event.pull_request.head.ref }}
        with:
          repository: ${{ steps.find_forks.outputs.user_fork_url }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: api

      - name: Use author's API repo if it exists
        uses: gradle/gradle-build-action@v2
        if: steps.find_forks.outputs.target_branch_found == 'true'
        with:
          arguments: publishToMavenLocal
          build-root-directory: api

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: geyser

      - name: Build Geyser
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: geyser

      - name: Archive artifacts (Geyser Fabric)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Fabric
          path: bootstrap/fabric/build/libs/Geyser-Fabric.jar

      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Standalone
          path: bootstrap/standalone/build/libs/Geyser-Standalone.jar

      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Spigot
          path: bootstrap/spigot/build/libs/Geyser-Spigot.jar

      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser BungeeCord
          path: bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar

      - name: Archive artifacts (Geyser Sponge)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Sponge
          path: bootstrap/sponge/build/libs/Geyser-Sponge.jar

      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Velocity
          path: bootstrap/velocity/build/libs/Geyser-Velocity.jar
